# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - name: Open Auto Commit Tistory Git Action Directory
      working-directory: AutoCommitTistory/auto_commit_tistory_git_action
      run: |
        ls -la
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test echo
      run: |
        echo ${{ secrets.OUTPUT_TYPE }}
    - name: Run Python
      run: |
        python3 hello.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f auto_commit_tistory_git_action/requirements.txt ]; then pip install -r auto_commit_tistory_git_action/requirements.txt; fi
    - name: Run Tistory test
      run: |
        python auto_commit_tistory_git_action/main.py
      env:
        MY_GITHUB_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
        APP_ID: ${{ secrets.APP_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        STATE_PARAM: ${{ secrets.STATE_PARAM }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        OUTPUT_TYPE: ${{ secrets.OUTPUT_TYPE }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
