name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run main.py
      run: |
        python main.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        APP_ID: ${{ secrets.APP_ID }}
        MY_GITHUB_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        STATE_PARAM: ${{ secrets.STATE_PARAM }}
        USERNAME: ${{ secrets.USERNAME }}