name: tistory_auto_commit

on:
  schedule:
    - cron: '45 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run main.py
        run: |
          python main.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
          JSON_FILE_NAME: ${{ secrets.JSON_FILE_NAME }}
          MY_GITHUB_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          STATE_PARAM: ${{ secrets.STATE_PARAM }}
          USERNAME: ${{ secrets.USERNAME }}